# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3d0aaff7acc735a362ce2cd6e3ea42bf11fb629f49cbe88a2f5345420611283c756461c77c574d37a0a770f510d8f152aa9e4c8355728be5e2e71f9be6cc77e6

test:
  secret_key_base: 4d6b3dbe90978fc802c6b4fd4c13fab422904c47d1830174e1799a29279e53fb9a7c25cd74b9d24addd5af1561bb5161c755b4395a2d2d99bae30921fad71e88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
